### ISSUE TITLE
500 Internal Server Error on Projects screen

### ISSUE THREAD

**Issue by warply** [stgeneral/redmine-progressive-projects-list#72] opened 2017-02-22 13:08 UTC
I receive an Internal Server Error on Projects screen when i Enable the option " Show projects' progress"
Below you can the error from my log.

 Rendered projects/index.html.erb within layouts/base (261.5ms)
Completed 500 Internal Server Error in 300ms (ActiveRecord: 64.4ms)

ActionView::Template::Error (undefined method `closed_pourcent' for #<Version:0x007fa1845998b8>):
     9: <h2><%= l(:label_project_plural) %></h2>
    10:
    11: <div id="projects-index">
    12: <%= render_project_hierarchy(@projects) %>
    13: </div>
    14:
    15: <% if User.current.logged? %>
  app/helpers/application_helper.rb:282:in `block in render_project_nested_lists'
  app/helpers/application_helper.rb:267:in `each'
  app/helpers/application_helper.rb:267:in `render_project_nested_lists'
  app/views/projects/index.html.erb:12:in `_app_views_projects_index_html_erb___1495844167746176069_70165935928220'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by stgeneral** [comment] 2017-02-22 14:09
Please use version of plugin that supports your version of Redmine - https://github.com/stgeneral/redmine-progressive-projects-list#compatibility

This issue is duplicate of #63 and #44, some more details can be found there.

**Closed by stgeneral** 2017-02-22 14:09 UTC
