### ISSUE TITLE
ActionView::Template::Error

### ISSUE THREAD

**Issue by mmxbow** [stgeneral/redmine-progressive-projects-list#81] opened 2018-08-22 06:34 UTC
Environment:
* Ubuntu 18.04 server
* Ruby 2.5.1
* Redmine 3.4.6
* Rails 4.2.8

After installing the plugin i've got a error:
<pre><code>
ActionView::Template::Error incomplete format specifier; use %% (double %) instead
</code></pre>

I made a correction in the file lib/progressive/projects_helper_patch.rb:

the line 48:
<pre><code class="ruby">
s << progress_bar([project.issues_close_percent, project.issues_completed_percent], :width => '30em', :legend => '%0.0f%' % project.issues_closed_percent)
</code></pre>
was replaced by:
<pre><code class="ruby">
s << progress_bar([project.issues_close_percent, project.issues_completed_percent], :width => '30em', :legend => '%0.0f%%' % project.issues_closed_percent)
</code></pre>

The problem was gone.

**Comment by mmxbow** [comment] 2018-08-22 06:39
I think the line 60 in the same file need to be corrected too:
replace format '%0.0f%' by '%0.0f%%'

**Comment by stgeneral** [comment] 2018-08-22 06:41
@mmxbow thanks for the report and attention to the plugin!

I suppose that issue is caused by Ruby 2.5.1. It seems that Redmine itself was not tested against the 2.5 (see http://www.redmine.org/projects/redmine/wiki/RedmineInstall).

These lines were copied from the Redmine's code. So, you might experience other issues with Redmine. Maybe you should consider downgrading Ruby to officially supported version 2.4.

**Comment by kulombok** [comment] 2018-09-06 06:13
I have the same issue with the same ruby version 2.5.1
For now, would you like to tell me how to uninstall this plugin ?
I looking forward when its support to ruby 2.5 thx

**Comment by stgeneral** [comment] 2018-09-06 07:51
> I have the same issue with the same ruby version 2.5.1

Thanks for confirming.

> I looking forward when its support to ruby 2.5 thx

Is your clean Redmine setup works well with Ruby 2.5?

**Comment by stgeneral** [comment] 2019-10-29 09:51
Should be fixed by #84.

**Closed by stgeneral** 2019-10-29 09:51 UTC
Labels: enhancement
